name: Refresh Starter Script Index

on:
  pull_request_target:
    types: 
      - closed
  workflow_dispatch:

jobs:
  reindex:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Reindex scripts
        run: |
          echo Preparing reindex operation...
          chmod +x ./dtssview.sh
          echo Reindexing scripts...
          ./dtssview.sh . > ./ScriptIndex.json
      - name: Push updated index
        run: |
          git config --global user.name "CodingWonders"
          git config --global user.email "101426328+CodingWonders@users.noreply.github.com"
          git add ./ScriptIndex.json
          git commit -am "Refreshed Script Index"
          git push
